{% set name = "setuptools-markdown" %}
{% set version = "0.3" %}
{% set hash_type = "sha256" %}
{% set hash = "89612f5cd790b7fcb25c15df25d6487c3cb2ff169a7b322012e747bb3de30d84" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  {{ hash_type }}: {{ hash }}

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  noarch: python

requirements:
  build:
    - pip
    - python
    - setuptools        
  run:
    - python    
    - pypandoc

test:
  imports:
    - setuptools_markdown

about:
  home: https://github.com/msabramo/setuptools-markdown
  license: MIT
  license_file: LICENSE-MIT
  summary: Use Markdown for your project description
  dev_url: https://github.com/msabramo/setuptools-markdown

extra:
  recipe-maintainers:
    - nicoddemus
