travis:
  secure:
    BINSTAR_TOKEN: SKiFQjCrhDG9d3fvXJJaptbnqQ/jykTCzq2HwqqmUzyeV/6gLSj97iTLluPC7LP0aOdYxZLzfeDYxC5UxIo8AXsXQVzyW0QB/ZcZIq8ZPgE0tDKffSLdQpcCkZHXl7WDopCH7xYf+vGFAPStgMySLH7mc6FCYlDfAyeC5rw+AIvlsszxdqy7X/kYJnKkmUMsSH8bFeAF9H4AVz3B22tSLpWLdSKefJ+9XdaDqW4lfdr19H6yTleDvqTyN/XbMzZlRjyWY9OICK8jMKvpEjJ/se/Z7AovKUY27KjWRP6i4rRSeqV9K9pZyfs21fZyY6DXr+jbvjaAiRThkSC6kwh3CxVGStBJjsMbuwnWQeIPH92gV0m7cbEpuFm0RKW0sNYih4L446IsJtXKMoCFauzknmoZlQXY5h7eW3LQCi6OGZWPprn1fmVzyTG0d7fi8O09dLTsCtUc8HiCMbbLCKa3wKihGSrHd5jCEuI3TTjCUmXzntenvmUN+B8/qjbX10o2YtZJyUOtmk2FCocSiCHtqQEOYfrG4Lv2LsTCIEyaq3J9n8QLfG8rdwOceJKRcXXcOWCg0npxR3EUY3H54dqecn2CwirTY2+FYqtGxPwL4mP7QX+wajp5F7c54B3t4wwF4ZHnyllKR/1MH09hXw7MZkXf+OpCKVFOHqv4IOm3Da0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
